name: deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest   #ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: ./backend
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: create env file
        working-directory: ./backend
        run: |
          pwd
          touch .env
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: build server files
        working-directory: ./backend
        run: |
          yarn run dev

  #### CD 위한 설정 추가 

      - name: zip file
        working-directory: ./backend
        run: zip -r track_1.zip ./dist ./scripts ./appspec.yml ./.env ./package.json ./yarn.lock ./nodemon.json

      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: upload to S3
        run: aws s3 cp --region ap-northeast-2 ./track_1.zip s3://nodejs-cd/deploy/

      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name Track-1_codedeploy
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name Track-1_CD_group
          --s3-location bucket=nodejs-cd,bundleType=zip,key=deploy/track_1.zip
